CREATE TABLE IF NOT EXISTS IrelandFacts (
			FactsID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
			UserID int FOREIGN KEY REFERENCES Users(UserID),
			factShortName VARCHAR(60) DEFAULT NULL,
			factLong VARCHAR(160) DEFAULT NULL
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
