CREATE TABLE IF NOT EXISTS QuizValues (
			QuizID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
			question VARCHAR(90) DEFAULT NULL,
			correctAnswer VARCHAR(90) DEFAULT NULL,
			wrongAnswer1 VARCHAR(90) DEFAULT NULL,
			wrongAnswer2 VARCHAR(90) DEFAULT NULL,
			wrongAnswer3 VARCHAR(90) DEFAULT NULL,
			FactsID int FOREIGN KEY REFERENCES IrelandFacts(FactsID),
			UserID int FOREIGN KEY REFERENCES Users(UserID)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unciode_ci AUTO_INCREMENT=1;
