CREATE TABLE IF NOT EXISTS Users (
	UserID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	username varchar(30) DEFAULT NULL,
	password varchar(30) DEFAULT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
